// ── Noms des classes Java par modèle ─────────────────────────────────────────

export const CLASSES = {
    partner: "com.axelor.apps.base.db.Partner",
    saleOrder: "com.axelor.apps.sale.db.SaleOrder",
    saleOrderLine: "com.axelor.apps.sale.db.SaleOrderLine",
    product: "com.axelor.apps.base.db.Product",
    opportunity: "com.axelor.apps.crm.db.Opportunity",
    lead: "com.axelor.apps.crm.db.Lead",
    invoice: "com.axelor.apps.account.db.Invoice",
    project: "com.axelor.apps.project.db.Project",
    timesheet: "com.axelor.apps.hr.db.Timesheet",
    timesheetLine: "com.axelor.apps.hr.db.TimesheetLine",
    jobPosition: "com.axelor.apps.hr.db.JobPosition",
    projectTask: "com.axelor.apps.project.db.ProjectTask",
    traceBack: "com.axelor.apps.base.db.TraceBack",
} as const;

// ── Champs par modèle ─────────────────────────────────────────────────────────

export const PARTNER_FIELDS = [
    "id",
    "partnerSeq",
    "name",
    "firstName",
    "fullName",
    "simpleFullName",
    "fixedPhone",
    "mobilePhone",
    "taxNbr",
    "siren",
    "registrationCode",
    "webSite",
    "description",
    "jobTitle",
    "department",
    "isCustomer",
    "isSupplier",
    "isProspect",
    "isContact",
    "isEmployee",
    "isCompensation",
    "isInternal",
    "isCorporatePartner",
    "partnerTypeSelect",
    "titleSelect",
    "sizeSelect",
    "leadScoringSelect",
    "saleTurnover",
    "paymentDelay",
    "deliveryDelay",
    "headOfficeAddress",
    "importOrigin",
    "createdOn",
    "updatedOn",
];

export const PRODUCT_FIELDS = [
    "id",
    "code",
    "fullName",
    "name",
    "subtitle",
    "description",
    "internalDescription",
    "productTypeSelect",
    "productSubTypeSelect",
    "salePrice",
    "saleCurrency",
    "costPrice",
    "purchasePrice",
    "avgPrice",
    "unit",
    "salesUnit",
    "purchasesUnit",
    "sellable",
    "purchasable",
    "isModel",
    "procurementMethodSelect",
    "saleSupplySelect",
    "standardDelay",
    "productFamily",
    "productCategory",
    "isActivity",
    "archived",
    "startDate",
    "endDate",
    "createdOn",
    "updatedOn",
];

export const LEAD_FIELDS = [
    // Identification
    "id",
    "fullName",
    "firstName",
    "name",
    "simpleFullName",
    // Entreprise
    "enterpriseName",
    "department",
    "jobTitleFunction",
    // Contact
    "fixedPhone",
    "mobilePhone",
    "emailAddress",
    "webSite",
    // Statut / qualification
    "leadStatus",
    "leadScoringSelect",
    "source",
    "type",
    "isKeyAccount",
    "isNurturing",
    "isConverted",
    "lostReason",
    "lostReasonStr",
    // Localisation
    "primaryAddress",
    "primaryCity",
    "primaryPostalCode",
    "primaryState",
    "primaryCountry",
    // Responsable / équipe
    "user",
    "team",
    "company",
    // Divers
    "industrySector",
    "sizeSelect",
    "numberOfEmployees",
    "description",
    "contactDate",
    "archived",
    "createdOn",
    "updatedOn",
];

export const OPPORTUNITY_FIELDS = [
    // Identification
    "id",
    "opportunitySeq",
    "name",
    // Partenaires
    "partner",
    "contact",
    "user",
    "team",
    "company",
    // Statut / étape
    "opportunityStatus",
    "opportunityType",
    "opportunityRating",
    "source",
    "lostReason",
    "lostReasonStr",
    // Montants
    "amount",
    "probability",
    "worstCase",
    "bestCase",
    "recurrentAmount",
    "currency",
    // Dates
    "expectedCloseDate",
    "recurringStartDate",
    "recurringEndDate",
    "expectedDurationOfRecurringRevenue",
    // Descriptions
    "description",
    "customerDescription",
    // Divers
    "archived",
    "createdOn",
    "updatedOn",
];

export const SALE_ORDER_LINE_FIELDS = [
    "id",
    "sequence",
    "typeSelect",
    "productName",
    "product.id",
    "product.code",
    "product.name",
    "product.productFamily.name",
    "product.productCategory.name",
    "qty",
    "unit.name",
    "price",
    "priceDiscounted",
    "exTaxTotal",
    "saleOrder.id",
    "saleOrder.saleOrderSeq",
    "saleOrder.orderDate",
    "saleOrder.statusSelect",
    "saleOrder.clientPartner.name",
];

export const OPPORTUNITY_ANALYSIS_FIELDS = [
    "id",
    "name",
    "amount",
    "probability",
    "worstCase",
    "bestCase",
    "expectedCloseDate",
    "opportunityStatus",
    "partner",
    "user",
    "source",
    "createdOn",
];

export const SALE_ANALYSIS_FIELDS = [
    "id",
    "orderDate",
    "statusSelect",
    "invoicingState",
    "exTaxTotal",
    "amountInvoiced",
    "totalCostPrice",
    "totalGrossMargin",
    "marginRate",
    "clientPartner",
    "salespersonUser",
    "currency",
];

export const INVOICE_FIELDS = [
    "id",
    "invoiceId",
    "invoiceDate",
    "dueDate",
    "nextDueDate",
    "statusSelect",
    "operationTypeSelect",
    "partner",
    "contactPartner",
    "saleOrder",
    "project",
    "exTaxTotal",
    "taxTotal",
    "inTaxTotal",
    "amountPaid",
    "amountRemaining",
    "companyInTaxTotal",
    "companyInTaxTotalRemaining",
    "currency",
    "company",
    "paymentCondition",
    "paymentMode",
    "paymentDate",
    "externalReference",
    "internalReference",
    "validatedDateTime",
    "ventilatedDateTime",
    "createdOn",
    "updatedOn",
];

export const TIMESHEET_FIELDS = [
    "id",
    "fullName",
    "employee",
    "company",
    "fromDate",
    "toDate",
    "periodTotal",
    "statusSelect",
    "isCompleted",
    "sentDateTime",
    "validationDateTime",
    "validatedBy",
    "refusalDateTime",
    "refusedBy",
    "groundForRefusal",
    "createdOn",
    "updatedOn",
];

export const TIMESHEET_LINE_FIELDS = [
    "id",
    "date",
    "hoursDuration",
    "comments",
    "timesheet",
    "timesheet.employee",
    "timesheet.statusSelect",
    "project",
    "projectTask",
    "createdOn",
];

export const PROJECT_FIELDS = [
    // Identification
    "id",
    "code",
    "name",
    "fullName",
    "description",
    // Client / responsable
    "clientPartner",
    "contactPartner",
    "assignedTo",
    "team",
    "company",
    // Statut / avancement
    "projectStatus",
    "isBusinessProject",
    "percentageOfProgress",
    "percentageOfConsumption",
    // Dates
    "fromDate",
    "toDate",
    // Temps
    "estimatedTimeHrs",
    "soldTime",
    "spentTime",
    "plannedTime",
    "budgetedTime",
    // Financier
    "currency",
    "turnover",
    "realTurnover",
    "totalEstimatedCosts",
    "totalRealCosts",
    "totalInvoiced",
    // Divers
    "archived",
    "createdOn",
    "updatedOn",
];

export const PROJECT_ANALYSIS_FIELDS = [
    "id",
    "name",
    "clientPartner",
    "assignedTo",
    "projectStatus",
    "fromDate",
    "toDate",
    "soldTime",
    "spentTime",
    "plannedTime",
    "percentageOfProgress",
    "percentageOfConsumption",
    "totalInvoiced",
    "totalRealCosts",
    "isBusinessProject",
];

export const PROJECT_TASK_FIELDS = [
    "id",
    "name",
    "project",
    "taskStatus",
    "assignedTo",
    "priority",
    "parentTask",
    "taskDate",
    "taskDeadline",
    "progressSelect",
    "estimatedTime",
    "plannedTime",
    "spentTime",
    "description",
    "createdOn",
    "updatedOn",
];

export const JOB_POSITION_FIELDS = [
    "id",
    "jobTitle",
    "jobReference",
    "location",
    "company",
    "companyDepartment",
    "employee",
    "contractType",
    "statusSelect",
    "positionStatusSelect",
    "experienceSelect",
    "salary",
    "nbOpenJob",
    "nbPeopleHired",
    "publicationDate",
    "startingDate",
    "jobDescription",
    "profileWanted",
    "mailAccount",
    "archived",
    "createdOn",
    "updatedOn",
];

export const TRACEBACK_FIELDS = [
    "id",
    "date",
    "name",
    "exception",
    "message",
    "error",
    "cause",
    "origin",
    "ref",
    "refId",
    "categorySelect",
    "typeSelect",
    "batchId",
    "internalUser",
    "createdBy",
    "createdOn",
    "updatedOn",
    "archived",
];

export const TRACEBACK_DETAIL_FIELDS = [
    "id",
    "date",
    "name",
    "exception",
    "message",
    "error",
    "cause",
    "origin",
    "ref",
    "refId",
    "categorySelect",
    "typeSelect",
    "batchId",
    "trace",
    "internalUser",
    "createdBy",
    "updatedBy",
    "createdOn",
    "updatedOn",
    "archived",
];

export const SALE_ORDER_FIELDS = [
    // Identification
    "id",
    "saleOrderSeq",
    "fullName",
    "title",
    "externalReference",
    "orderNumber",
    "versionNumber",
    // Statut
    "statusSelect",
    "invoicingState",
    "deliveryState",
    "orderingStatus",
    "saleOrderTypeSelect",
    // Dates
    "creationDate",
    "orderDate",
    "confirmationDateTime",
    "endOfValidityDate",
    "shipmentDate",
    "estimatedDeliveryDate",
    "estimatedShippingDate",
    // Partenaires (retournent {id, $version, name/fullName})
    "clientPartner",
    "invoicedPartner",
    "deliveredPartner",
    "contactPartner",
    "salespersonUser",
    "confirmedByUser",
    // Société / devise
    "company",
    "currency",
    "companyCurrency",
    // Montants
    "exTaxTotal",
    "inTaxTotal",
    "taxTotal",
    "companyExTaxTotal",
    "amountInvoiced",
    "advanceTotal",
    "advancePaymentAmountNeeded",
    "totalCostPrice",
    "companyCostTotal",
    "marginRate",
    "markup",
    "totalGrossMargin",
    "priceBeforeGlobalDiscount",
    "discountAmount",
    "discountTypeSelect",
    "shippingCost",
    // Paiement / livraison
    "paymentCondition",
    "paymentMode",
    "incoterm",
    "shipmentMode",
    "freightCarrierMode",
    "carrierPartner",
    "forwarderPartner",
    "deliveryCondition",
    // Adresses (champs texte dénormalisés)
    "mainInvoicingAddressStr",
    "deliveryAddressStr",
    // Logistique
    "stockLocation",
    "toStockLocation",
    "directOrderLocation",
    "standardDelay",
    // Notes et commentaires
    "description",
    "internalNote",
    "invoiceComments",
    "deliveryComments",
    "pickingOrderComments",
    "proformaComments",
    "productionNote",
    "specificNotes",
    // Contrat / abonnement
    "template",
    "oneoffSale",
    "contractStartDate",
    "contractEndDate",
    "contractPeriodInMonths",
    "currentContractPeriodEndDate",
    "nextInvoicingDate",
    "nextInvoicingStartPeriodDate",
    "nextInvoicingEndPeriodDate",
    // Projet
    "project",
    // Divers
    "inAti",
    "hideDiscount",
    "groupProductsOnPrintings",
    "createdOn",
    "updatedOn",
];
