// ── Noms des classes Java par modèle ─────────────────────────────────────────

export const CLASSES = {
    partner: "com.axelor.apps.base.db.Partner",
    saleOrder: "com.axelor.apps.sale.db.SaleOrder",
} as const;

// ── Champs par modèle ─────────────────────────────────────────────────────────

export const PARTNER_FIELDS = [
    "id",
    "partnerSeq",
    "name",
    "firstName",
    "fullName",
    "simpleFullName",
    "fixedPhone",
    "mobilePhone",
    "taxNbr",
    "siren",
    "registrationCode",
    "webSite",
    "description",
    "jobTitle",
    "department",
    "isCustomer",
    "isSupplier",
    "isProspect",
    "isContact",
    "isEmployee",
    "isCompensation",
    "isInternal",
    "isCorporatePartner",
    "partnerTypeSelect",
    "titleSelect",
    "sizeSelect",
    "leadScoringSelect",
    "saleTurnover",
    "paymentDelay",
    "deliveryDelay",
    "headOfficeAddress",
    "importOrigin",
    "createdOn",
    "updatedOn",
];

export const SALE_ORDER_FIELDS = [
    // Identification
    "id",
    "saleOrderSeq",
    "fullName",
    "title",
    "externalReference",
    "orderNumber",
    "versionNumber",
    // Statut
    "statusSelect",
    "invoicingState",
    "deliveryState",
    "orderingStatus",
    "saleOrderTypeSelect",
    // Dates
    "creationDate",
    "orderDate",
    "confirmationDateTime",
    "endOfValidityDate",
    "shipmentDate",
    "estimatedDeliveryDate",
    "estimatedShippingDate",
    // Partenaires (retournent {id, $version, name/fullName})
    "clientPartner",
    "invoicedPartner",
    "deliveredPartner",
    "contactPartner",
    "salespersonUser",
    "confirmedByUser",
    // Société / devise
    "company",
    "currency",
    "companyCurrency",
    // Montants
    "exTaxTotal",
    "inTaxTotal",
    "taxTotal",
    "companyExTaxTotal",
    "amountInvoiced",
    "advanceTotal",
    "advancePaymentAmountNeeded",
    "totalCostPrice",
    "companyCostTotal",
    "marginRate",
    "markup",
    "totalGrossMargin",
    "priceBeforeGlobalDiscount",
    "discountAmount",
    "discountTypeSelect",
    "shippingCost",
    // Paiement / livraison
    "paymentCondition",
    "paymentMode",
    "incoterm",
    "shipmentMode",
    "freightCarrierMode",
    "carrierPartner",
    "forwarderPartner",
    "deliveryCondition",
    // Adresses (champs texte dénormalisés)
    "mainInvoicingAddressStr",
    "deliveryAddressStr",
    // Logistique
    "stockLocation",
    "toStockLocation",
    "directOrderLocation",
    "standardDelay",
    // Notes et commentaires
    "description",
    "internalNote",
    "invoiceComments",
    "deliveryComments",
    "pickingOrderComments",
    "proformaComments",
    "productionNote",
    "specificNotes",
    // Contrat / abonnement
    "template",
    "oneoffSale",
    "contractStartDate",
    "contractEndDate",
    "contractPeriodInMonths",
    "currentContractPeriodEndDate",
    "nextInvoicingDate",
    "nextInvoicingStartPeriodDate",
    "nextInvoicingEndPeriodDate",
    // Projet
    "project",
    // Divers
    "inAti",
    "hideDiscount",
    "groupProductsOnPrintings",
    "createdOn",
    "updatedOn",
];
